server:
  port: 10004
  servlet:
    context-path: /agent
  tomcat:
    accept-count: 1000 # Maximum queue length for incoming connection requests when all possible request processing threads are in use
    threads:
      max: 1000 # Maximum amount of worker threads.
      min-spare: 10 # Minimum amount of worker threads.

spring:
  application:
    name: agent-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        ip: ${NACOS_DISCOVERY_IP:}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:127.0.0.1:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

zk:
  addr: ${ZK_ADDR:127.0.0.1:2181}

agent:
  version: @project.version@
  download-dir: download
  android:
    enabled: true
    adb-path:
    scrcpy-version: 1.25
    scrcpy-server-path: vendor/scrcpy/scrcpy-server-v1.25
  iOS:
    realDevice:
      enabled: false
    emulator:
      enabled: false
      #  ns for nanoseconds
      #  us for microseconds
      #  ms for milliseconds
      #  s for seconds
      #  m for minutes
      #  h for hours
      #  d for days
      scan-period: 30s
  appium:
    js-path:
  plugin:
    base-dir: ${agent.download-dir}/plugins

logging:
  level:
    root: info
  file:
    name: logs/${spring.application.name}.log