server:
  port: 8811
  servlet:
    context-path: /auth
  tomcat:
    accept-count: 1000 # Maximum queue length for incoming connection requests when all possible request processing threads are in use
    threads:
      max: 1000 # Maximum amount of worker threads.
      min-spare: 10 # Minimum amount of worker threads.

spring:
  application:
    name: auth-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        ip: ${NACOS_DISCOVERY_IP:}
  datasource:
    url: jdbc:mysql://${AUTH_MYSQL_ADDR:127.0.0.1:3306}/auth?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: ${AUTH_MYSQL_USERNAME:root}
    password: ${AUTH_MYSQL_PWD:yqhp@123..Aa88}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      idle-timeout: 60000 # 空闲连接，最大存活时间
      connection-test-query: SELECT 1
      connection-timeout: 10000
      max-lifetime: 120000

  redis:
    host: ${AUTH_REDIS_HOST:127.0.0.1}
    port: ${AUTH_REDIS_PORT:6379}
    password: ${AUTH_REDIS_PWD:yqhp@123..Aa88}

mybatis-plus:
  type-enums-package: com.yqhp.auth.repository.enums
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath:/mapper/**.xml

#  ns for nanoseconds
#  us for microseconds
#  ms for milliseconds
#  s for seconds
#  m for minutes
#  h for hours
#  d for days
token:
  expire: 365d

logging:
  level:
    root: info
  file:
    name: logs/${spring.application.name}.log