server:
  port: 8887
  servlet:
    context-path: /console
  tomcat:
    accept-count: 1000 # Maximum queue length for incoming connection requests when all possible request processing threads are in use
    threads:
      max: 1000 # Maximum amount of worker threads.
      min-spare: 10 # Minimum amount of worker threads.

spring:
  application:
    name: console-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        ip: ${NACOS_DISCOVERY_IP}
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:127.0.0.1:9094}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: console
      enable-auto-commit: true
      max-poll-records: 1000
  #    properties:
  #      security:
  #        protocol: SASL_PLAINTEXT
  #      sasl:
  #        mechanism: PLAIN
  #        jaas:
  #          config: 'org.apache.kafka.common.security.scram.ScramLoginModule required username="admin" password="admin@123";'

  datasource:
    url: jdbc:mysql://${CONSOLE_MYSQL_ADDR:127.0.0.1:3306}/console?characterEncoding=utf-8&useSSL=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: ${CONSOLE_MYSQL_USERNAME:root}
    password: ${CONSOLE_MYSQL_PWD:yqhp@123..Aa88}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      idle-timeout: 60000 # 空闲连接，最大存活时间
      connection-test-query: SELECT 1
      connection-timeout: 10000
      max-lifetime: 120000

  redis:
    host: ${CONSOLE_REDIS_HOST:127.0.0.1}
    port: ${CONSOLE_REDIS_PORT:6379}
    password: ${CONSOLE_REDIS_PWD:yqhp@123..Aa88}

zk:
  addr: ${ZK_ADDR:127.0.0.1:2181}

mybatis-plus:
  type-enums-package: com.yqhp.console.repository.enums
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  mapper-locations: classpath:/mapper/**.xml

logging:
  level:
    root: info
  file:
    name: ${user.home}/yqhp/console/logs/${spring.application.name}.log