server:
  port: 8866
  servlet:
    context-path: /oss
  tomcat:
    accept-count: 1000 # Maximum queue length for incoming connection requests when all possible request processing threads are in use
    threads:
      max: 1000 # Maximum amount of worker threads.
      min-spare: 10 # Minimum amount of worker threads.

spring:
  application:
    name: file-service

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
        ip: ${NACOS_DISCOVERY_IP}

  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

oss:
  minio:
    public-endpoint: ${MINIO_PUBLIC_ENDPOINT}
    endpoint: ${MINIO_ENDPOINT:http://127.0.0.1:9000}
    bucket: ${MINIO_BUCKET:yqhp}
    accessKey: ${MINIO_ACCESS_KEY:yqhp}
    secretKey: ${MINIO_SECRET_KEY:yqhp@123..Aa88}

logging:
  level:
    root: info
  file:
    name: ${user.home}/yqhp/file/logs/${spring.application.name}.log