name: Agent Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run: mvn install
      - name: copy
        run: cp -r agent/agent-web/target/lib* agent/agent-web/target/*.jar .
      - name: zip
        run: zip -r yqhp-agent.zip lib* *.jar vendor
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GIT_TOKEN }}
          file: yqhp-agent.zip
          asset_name: yqhp-agent.zip
          tag: agent
          overwrite: true
          body: "yqhp-agent release"