name: Update Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - README.MD
      - .github/workflows/DockerHub.yml
jobs:
  dockerHubDescription:
    if: startsWith(github.repository, 'tony252/yqhp')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tony252/yqhp
        short-description: ${{ github.event.repository.description }}
        readme-filepath: ./README.md
