name:  Maven Push DockerHub

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  install:
    runs-on:  ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
        run:  mvn install 
      - uses: actions/upload-artifact@v3
        with:
          name: auth
          path: |
            auth
      - uses: actions/upload-artifact@v3
        with:
          name: console
          path: |
            console            
        
        
        
  auth:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: auth
      - name: Display structure of downloaded files
        run: ls -R 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: 
            tony252/yqhp:latest
            tony252/yqhp:0.0.1
