name:  Maven Push DockerHub

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  install:
    runs-on:  ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
          cache: maven
      - name: Build with Maven
        run:  mvn install        
  auth:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Cache maven packages
        uses: actions/cache@v3
        with:
          path: |
            ~/auth
          key: ${{ runner.os }}-maven-${{ hashFiles('**/auth-web-0.0.1.jar') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      -
        run: java -jar auth-web-0.0.1.jar
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: auth
        run: cd auth     
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./auth
          push: true
          tags: tony252/yqhp:latest
